# Generated by Django 5.2.12 on 2026-04-03 09:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnl_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propaccount',
            name='activation_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='propaccount',
            name='broker',
            field=models.CharField(choices=[('tradovate', 'Tradovate'), ('rithmic', 'Rithmic'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='propaccount',
            name='profit_target_hit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='contract_type',
            field=models.CharField(choices=[('mini', 'Mini'), ('micro', 'Micro'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='trade',
            name='contracts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trade',
            name='broker_fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='pnl_calendar.propaccount')),
            ],
            options={
                'ordering': ('payout_date', 'id'),
            },
        ),
    ]
