# Generated by Django 5.2.12 on 2026-04-03 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnl_calendar', '0002_propaccount_activation_fee_propaccount_broker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyTradingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='propaccount',
            name='is_copy_lead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='source_trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copied_trades', to='pnl_calendar.trade'),
        ),
        migrations.AddField(
            model_name='propaccount',
            name='copy_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='pnl_calendar.copytradinggroup'),
        ),
    ]
