# Generated by Django 5.2.12 on 2026-04-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnl_calendar', '0003_copytradinggroup_propaccount_is_copy_lead_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='propaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_copy_lead', True)), fields=('copy_group',), name='one_copy_lead_per_group'),
        ),
    ]
