# Generated by Django 5.2.12 on 2026-04-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnl_calendar', '0005_propaccount_evaluation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='propaccount',
            name='traildown_type',
            field=models.CharField(choices=[('intraday', 'Intraday'), ('end_of_day', 'End of day')], default='intraday', max_length=20),
        ),
    ]
