# Generated by Django 5.2.12 on 2026-04-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnl_calendar', '0006_propaccount_traildown_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='propaccount',
            name='inactive_reason',
            field=models.CharField(blank=True, choices=[('', 'None'), ('evaluation_blown', 'Evaluation blown'), ('max_payouts_received', 'Max payouts received'), ('funding_blown', 'Funding blown')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='propaccount',
            name='is_hidden_from_accounts',
            field=models.BooleanField(default=False),
        ),
    ]
