# Generated by Django 5.2.12 on 2026-04-06 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnl_calendar', '0007_propaccount_inactive_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingDayStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('status', models.CharField(choices=[('no_trade', 'No trade'), ('market_closed', 'Market closed')], max_length=20)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_statuses', to='pnl_calendar.propfirm')),
            ],
            options={
                'ordering': ('-trade_date',),
                'unique_together': {('firm', 'trade_date')},
            },
        ),
    ]
